In [116]:
import pandas as pd

In [117]:
results = pd.read_csv("Data/results.csv")
plr = pd.read_csv("Data/playerattributes.csv")

In [118]:
results = results[["Country", "Score", "Pos.", "Pts"]]
results

         Country  Score  Pos.  Pts
0        Uruguay      3     5   12
1         Russia      3     8    8
2   Saudi Arabia      1    26    3
3          Egypt      1    31    0
4          Spain      2    10    6
5       Portugal      2    13    5
6           Iran      1    18    4
7        Morocco      1    27    1
8         France      7     1   19
9        Denmark      2    11    6
10          Peru      1    20    3
11     Australia      1    28    1
12       Croatia      6     2   14
13     Argentina      2    16    4
14       Nigeria      1    21    3
15       Iceland      1    29    1
16        Brazil      3     6   10
17   Switzerland      2    14    5
18        Serbia      1    22    3
19    Costa Rica      1    30    1
20        Sweden      3     7    9
21        Mexico      2    12    6
22   South Korea      1    19    3
23       Germany      1    23    3
24       Belgium      5     3   18
25       England      4     4   10
26       Tunisia      1    24    3
27        Panama      1    32    0
28      Colombia      2     9    7
29         Japan      2    15    4
30       Senegal      1    17    4
31        Poland      1    25    3

In [119]:
plr = plr[["short_name","long_name", "nationality", "movement_acceleration", "movement_agility", "movement_balance", "power_jumping", "pace", "movement_reactions", "movement_sprint_speed", "power_stamina", "power_strength"]]
plr

,short_name,long_name,nationality,movement_acceleration,movement_agility,movement_balance,power_jumping,pace,movement_reactions,movement_sprint_speed,power_stamina,power_strength
0,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,Portugal,89,89,63,95,90.0,96,91,92,80
1,L. Messi,Lionel Andrés Messi Cuccittini,Argentina,92,90,95,68,89.0,95,87,73,59
2,Neymar,Neymar da Silva Santos Júnior,Brazil,94,96,82,61,92.0,88,90,78,53
3,M. Neuer,Manuel Neuer,Germany,58,52,35,78,NaN,85,61,44,83
4,L. Suárez,Luis Alberto Suárez Díaz,Uruguay,88,86,60,69,82.0,93,77,89,80
...,...,...,...,...,...,...,...,...,...,...,...,...
17949,A. Kelsey,Adam Kelsey,England,24,38,26,31,NaN,40,32,28,50
17950,J. Young,Jordan Young,Scotland,66,60,77,73,58.0,54,51,33,32
17951,J. Keeble,Jack Keeble,England,66,45,48,54,63.0,48,60,52,42
17952,B. Richardson,Barry Richardson,England,25,35,44,51,NaN,51,25,32,47
17953,T. Käßemodel,Tommy Käßemodel,Germany,25,40,52,28,23.0,47,22,30,37

In [120]:
merged =  pd.merge(results, plr, left_on = 'Country', right_on = 'nationality')
merged

,Country,Score,Pos.,Pts,short_name,long_name,nationality,movement_acceleration,movement_agility,movement_balance,power_jumping,pace,movement_reactions,movement_sprint_speed,power_stamina,power_strength
0,Uruguay,3,5,12,L. Suárez,Luis Alberto Suárez Díaz,Uruguay,88,86,60,69,82.0,93,77,89,80
1,Uruguay,3,5,12,D. Godín,Diego Roberto Godín Leal,Uruguay,62,63,58,89,65.0,85,67,67,80
2,Uruguay,3,5,12,E. Cavani,Edinson Roberto Cavani Gómez,Uruguay,75,81,59,88,77.0,91,78,92,74
3,Uruguay,3,5,12,J. Giménez,José María Giménez de Vargas,Uruguay,68,57,50,90,70.0,76,72,68,84
4,Uruguay,3,5,12,F. Muslera,Néstor Fernando Muslera Micol,Uruguay,60,68,62,84,NaN,78,62,45,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11672,Poland,1,25,3,K. Miroszka,Krzysztof Miroszka,Poland,68,56,73,64,69.0,41,69,37,60
11673,Poland,1,25,3,S. Kogut,Szczepan Kogut,Poland,61,59,59,88,60.0,48,60,50,73
11674,Poland,1,25,3,S. Więckowicz,Szymon Więckowicz,Poland,21,31,21,35,NaN,28,27,21,55
11675,Poland,1,25,3,K. Tomasik,Kacper Tomasik,Poland,21,37,23,38,NaN,38,16,23,54
11676,Poland,1,25,3,H. Maślanka,Hubert Maślanka,Poland,57,57,67,62,63.0,49,68,57,54

In [121]:
# export the attributes merged
merged.to_csv("Data/merged_attributes.csv")

In [122]:
grouped = merged[["Country", "Pos.", "Pts", "movement_acceleration", "movement_agility", "movement_balance", "power_jumping", "pace", "movement_reactions", "movement_sprint_speed", "power_stamina", "power_strength"]].groupby(["Country"]).mean()

In [123]:
grouped
# export the mean of all the players' attributes grouped by their country
grouped.to_csv("Data/grouped_by_country.csv")

In [127]:
# using sklearn

import statsmodels.api as sm
import numpy as np

# perform standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = grouped[["movement_acceleration", "movement_agility", "movement_balance", "power_jumping", "pace", "movement_reactions", "movement_sprint_speed", "power_stamina", "power_strength"]]
y = grouped["Pos."]
scaler.fit(X, y)
X_tr = scaler.transform(X)

# find the r value
X_tr = sm.add_constant(X_tr)
model = sm.OLS(y, X_tr).fit()
print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:                   Pos.   R-squared:                       0.338
Model:                            OLS   Adj. R-squared:                  0.054
Method:                 Least Squares   F-statistic:                     1.190
Date:                Tue, 22 Nov 2022   Prob (F-statistic):              0.351
Time:                        23:47:13   Log-Likelihood:                -106.96
No. Observations:                  31   AIC:                             233.9
Df Residuals:                      21   BIC:                             248.3
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         16.4194      1.664      9.868      0.000      12.959      19.880
x1            -8.3199     12.843     -0.648      0.524     -35.029      18.389
x2             6.1782      4.958      1.246      0.226      -4.132      16.488
x3             6.0067      4.166      1.442      0.164      -2.658      14.671
x4             0.3210      2.604      0.123      0.903      -5.095       5.737
x5             0.4454      6.392      0.070      0.945     -12.847      13.738
x6            -4.0672      2.329     -1.746      0.095      -8.910       0.776
x7             2.8372     17.057      0.166      0.869     -32.634      38.308
x8            -3.5862      4.957     -0.723      0.477     -13.895       6.723
x9            10.3493      5.226      1.981      0.061      -0.518      21.217
==============================================================================
Omnibus:                        0.580   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.748   Jarque-Bera (JB):                0.653
Skew:                          -0.103   Prob(JB):                        0.722
Kurtosis:                       2.320   Cond. No.                         27.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [126]:
# using statsmodels

import statsmodels.api as sm
import numpy as np
from scipy import stats

# perform standardization
std_group = grouped.select_dtypes(include=[np.number]).dropna().apply(stats.zscore)
X = std_group[["movement_acceleration", "movement_agility", "movement_balance", "power_jumping", "pace", "movement_reactions", "movement_sprint_speed", "power_stamina", "power_strength"]]
y = std_group["Pos."]

# export standardized data to csv
results = pd.merge(y, X, on="Country")
results.to_csv("Data/standardized_merged_data.csv")

# find the r value
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
print_model = model.summary()
print(print_model)

              const  movement_acceleration  movement_agility  \
Country
Argentina       1.0              -0.156898         -0.000437
Australia       1.0              -0.206956         -0.791441
Belgium         1.0              -0.430452          0.212634
Brazil          1.0               0.519892          0.707941
Colombia        1.0               0.536411          0.314611
Costa Rica      1.0               1.650841          1.258228
Croatia         1.0              -0.947109         -1.414919
Denmark         1.0              -0.959481         -0.744458
Egypt           1.0               0.461904          0.433498
England         1.0               0.169037         -0.268446
France          1.0              -0.327517         -0.462720
Germany         1.0              -0.683284         -0.520996
Iceland         1.0              -0.180520         -0.030361
Iran            1.0               0.574194          0.690471
Japan           1.0              -1.223156         -0.231525
Mexico          1.0              -0.438284         -0.126745
Morocco         1.0               2.015996          3.129645
Nigeria         1.0               2.967022          1.567435
Panama          1.0              -0.036299         -0.441357
Peru            1.0               1.140901          0.933819
Poland          1.0              -1.212579         -0.822620
Portugal        1.0               0.314795          1.256281
Russia          1.0              -0.996807         -1.331633
Saudi Arabia    1.0              -0.537634         -0.449420
Senegal         1.0               1.353636          0.278412
Serbia          1.0              -1.254208         -1.626738
Spain           1.0              -0.381993          0.173827
Sweden          1.0              -0.808172         -0.552973
Switzerland     1.0              -1.227412         -1.770957
Tunisia         1.0               0.149533          0.735229
Uruguay         1.0               0.154599         -0.104284

              movement_balance  power_jumping      pace  movement_reactions  \
Country
Argentina             0.573270       0.064575 -0.156794            0.451621
Australia            -0.515635      -0.782389  0.107629           -1.882287
Belgium              -0.063685       0.921105 -0.099375            0.449093
Brazil                0.119219       0.112443  0.162956            1.891486
Colombia              0.481973       0.559707  0.459405           -0.268993
Costa Rica            0.709103       2.200125  1.953187            1.095887
Croatia              -2.386926      -1.429078 -0.806953            0.415908
Denmark              -0.682651      -0.102839 -0.528287           -0.821584
Egypt                 1.087808      -1.336695  0.479275            0.699441
England               0.215929      -0.190458  0.027079           -1.648674
France                0.102796      -0.033168 -0.367432           -0.239098
Germany              -0.747270       0.130544 -0.437594           -0.206211
Iceland               0.262063       1.170840 -0.423734           -0.060934
Iran                 -0.383267      -0.774945  2.690935            1.097912
Japan                 0.941960      -0.716318 -0.912789           -1.315675
Mexico                1.157352      -0.119144 -0.282677           -0.584261
Morocco               1.814189      -1.120597  1.004626            0.737254
Nigeria               0.861569       1.622759  2.555904           -0.188779
Panama               -1.078555      -0.354205 -1.386367           -0.048755
Peru                  2.056058       0.997106  0.513301           -0.082884
Poland               -0.804117      -0.119144 -0.895752           -1.151186
Portugal              0.850618       0.421849  0.429025            1.820151
Russia               -0.828166      -1.750680 -0.419089           -0.147574
Saudi Arabia          0.605279      -0.312712 -0.262350           -2.044723
Senegal              -0.924051       2.789053  1.203301            0.259805
Serbia               -2.156325      -0.269746 -1.472189            1.259147
Spain                 0.358824       0.158770 -0.684249            0.949291
Sweden               -1.124958      -1.113408 -0.608491           -0.522104
Switzerland          -0.645211      -0.285887 -0.955787           -1.157192
Tunisia              -0.124047      -0.591433 -0.868648            0.177508
Uruguay               0.266854       0.253969 -0.018064            1.066412

              movement_sprint_speed  power_stamina  power_strength
Country
Argentina                 -0.250185      -0.085682       -0.587062
Australia                 -0.042363      -0.695619       -0.378647
Belgium                   -0.518033      -0.922785       -0.564657
Brazil                     0.492468       0.764027        0.498015
Colombia                   0.370573       0.817525       -0.159320
Costa Rica                 1.766858       1.061701        0.147210
Croatia                   -0.810356      -0.014583        1.027104
Denmark                   -0.535494      -0.002690        0.109678
Egypt                      0.626555       0.582723        1.117739
England                   -0.036014      -0.105596       -0.502970
France                    -0.434830      -0.711639       -0.177367
Germany                   -0.553550      -0.349714        0.193609
Iceland                    0.258299       2.000049        0.810853
Iran                       0.637118      -1.983738       -0.480868
Japan                     -1.319451      -0.817073       -1.848463
Mexico                    -0.677330      -0.792519       -1.403796
Morocco                    1.412765       0.262852       -0.708383
Nigeria                    3.090637       1.485662        1.579895
Panama                    -0.181534       1.103594        2.038598
Peru                       0.766268      -0.355752       -1.678351
Poland                    -1.281232      -0.894780       -0.141197
Portugal                   0.140443       0.607731       -0.513150
Russia                    -1.110850      -2.156032       -0.923703
Saudi Arabia              -0.600938      -1.104166       -1.216151
Senegal                    1.976153       1.947173        1.981869
Serbia                    -1.138333       0.496725        1.734265
Spain                     -0.410054       0.103691       -0.559276
Sweden                    -0.619279       0.204360        0.249000
Switzerland               -1.207319      -1.358169       -0.611386
Tunisia                    0.031712       0.625027        0.834180
Uruguay                    0.157297       0.287699        0.132732
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Pos.   R-squared:                       0.338
Model:                            OLS   Adj. R-squared:                  0.054
Method:                 Least Squares   F-statistic:                     1.190
Date:                Tue, 22 Nov 2022   Prob (F-statistic):              0.351
Time:                        23:45:26   Log-Likelihood:                -37.600
No. Observations:                  31   AIC:                             95.20
Df Residuals:                      21   BIC:                             109.5
Df Model:                           9
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                  1.195e-16      0.178   6.73e-16      1.000      -0.369       0.369
movement_acceleration    -0.8880      1.371     -0.648      0.524      -3.739       1.963
movement_agility          0.6594      0.529      1.246      0.226      -0.441       1.760
movement_balance          0.6411      0.445      1.442      0.164      -0.284       1.566
power_jumping             0.0343      0.278      0.123      0.903      -0.544       0.612
pace                      0.0475      0.682      0.070      0.945      -1.371       1.466
movement_reactions       -0.4341      0.249     -1.746      0.095      -0.951       0.083
movement_sprint_speed     0.3028      1.820      0.166      0.869      -3.483       4.089
power_stamina            -0.3827      0.529     -0.723      0.477      -1.483       0.718
power_strength            1.1045      0.558      1.981      0.061      -0.055       2.264
==============================================================================
Omnibus:                        0.580   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.748   Jarque-Bera (JB):                0.653
Skew:                          -0.103   Prob(JB):                        0.722
Kurtosis:                       2.320   Cond. No.                         27.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.