In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [24]:

web = f'https://en.wikipedia.org/wiki/National_team_appearances_in_the_FIFA_World_Cup'
response = requests.get(web)
content = response.text
soup = BeautifulSoup(content, 'lxml')
table = soup.find('table')

In [28]:
df=pd.DataFrame(pd.read_html(str(table))[0])

In [29]:
df

,Team,Appearances,Record streak,Active streak,Debut,Most recent,Best result (* = hosts)
0,Brazil,22,22,22,1930,2022,"Champions (1958, 1962, 1970, 1994, 2002)"
1,Germany,20,18,18,1934,2022,"Champions (1954, 1974*, 1990, 2014)"
2,Argentina,18,13,13,1930,2022,"Champions (1978*, 1986)"
3,Italy,18,14,0,1934,2014,"Champions (1934*, 1938, 1982, 2006)"
4,Mexico,17,8,8,1930,2022,"Quarterfinals (1970*, 1986*)"
...,...,...,...,...,...,...,...
74,Slovakia,1,1,0,2010,2010,Round of 16 (2010)
75,Bosnia and Herzegovina,1,1,0,2014,2014,Group Stage
76,Iceland,1,1,0,2018,2018,Group Stage
77,Panama,1,1,0,2018,2018,Group Stage
78,Qatar,1,1,0,2022,2022,TBD